export const All_CUISINES_REQUEST = "All_CUISINES_REQUEST";
export const All_CUISINES_SUCCESS = "All_CUISINES_SUCCESS";
export const All_CUISINES_FAIL = "All_CUISINES_FAIL";

export const NEW_CUISINES_REQUEST = "NEW_DELIVERYBOY_REQUEST";
export const NEW_CUISINES_SUCCESS = "NEW_DELIVERYBOY_SUCCESS";
export const NEW_CUISINES_RESET = "NEW_DELIVERYBOY_RESET";
export const NEW_CUISINES_FAIL = "NEW_DELIVERYBOY_FAIL";

export const DELETE_CUISINES_REQUEST = "DELETE_CUISINES_REQUEST";
export const DELETE_CUISINES_SUCCESS = "DELETE_CUISINES_SUCCESS";
export const DELETE_CUISINES_RESET = "DELETE_CUISINES_RESET";
export const DELETE_CUISINES_FAIL = "DELETE_CUISINES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";