export const All_QUESTION_REQUEST = "All_QUESTION_REQUEST";
export const All_QUESTION_SUCCESS = "All_QUESTION_SUCCESS";
export const All_QUESTION_FAIL = "All_QUESTION_FAIL";

export const NEW_QUESTION_REQUEST = "NEW_QUESTION_REQUEST";
export const NEW_QUESTION_SUCCESS = "NEW_QUESTION_SUCCESS";
export const NEW_QUESTION_RESET = "NEW_QUESTION_RESET";
export const NEW_QUESTION_FAIL = "NEW_QUESTION_FAIL";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_RESET = "UPDATE_QUESTION_RESET";
export const UPDATE_QUESTION_FAIL = "UPDATE_QUESTION_FAIL";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_RESET = "DELETE_QUESTION_RESET";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";

export const SINGLE_QUESTION_REQUEST = "SINGLE_QUESTION_REQUEST";
export const SINGLE_QUESTION_SUCCESS = "SINGLE_QUESTION_SUCCESS";
export const SINGLE_QUESTION_FAIL = "SINGLE_QUESTION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";