export const All_REFERRALAMOUNT_REQUEST = "All_REFERRALAMOUNT_REQUEST";
export const All_REFERRALAMOUNT_SUCCESS = "All_REFERRALAMOUNT_SUCCESS";
export const All_REFERRALAMOUNT_FAIL = "All_REFERRALAMOUNT_FAIL";

export const UPDATE_REFERRALAMOUNT_REQUEST = "UPDATE_REFERRALAMOUNT_REQUEST";
export const UPDATE_REFERRALAMOUNT_SUCCESS = "UPDATE_REFERRALAMOUNT_SUCCESS";
export const UPDATE_REFERRALAMOUNT_RESET = "UPDATE_REFERRALAMOUNT_RESET";
export const UPDATE_REFERRALAMOUNT_FAIL = "UPDATE_REFERRALAMOUNT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";