export const All_CUSTOMER_REQUEST = "All_CUSTOMER_REQUEST";
export const All_CUSTOMER_SUCCESS = "All_CUSTOMER_SUCCESS";
export const All_CUSTOMER_FAIL = "All_CUSTOMER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";