export const All_DELIVERYBOY_REQUEST = "All_DELIVERYBOY_REQUEST";
export const All_DELIVERYBOY_SUCCESS = "All_DELIVERYBOY_SUCCESS";
export const All_DELIVERYBOY_FAIL = "All_DELIVERYBOY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";