export const All_DELIVERYBOY_REQUEST = "All_DELIVERYBOY_REQUEST";
export const All_DELIVERYBOY_SUCCESS = "All_DELIVERYBOY_SUCCESS";
export const All_DELIVERYBOY_FAIL = "All_DELIVERYBOY_FAIL";

export const NEW_DELIVERYBOY_REQUEST = "NEW_DELIVERYBOY_REQUEST";
export const NEW_DELIVERYBOY_SUCCESS = "NEW_DELIVERYBOY_SUCCESS";
export const NEW_DELIVERYBOY_RESET = "NEW_DELIVERYBOY_RESET";
export const NEW_DELIVERYBOY_FAIL = "NEW_DELIVERYBOY_FAIL";

export const UPDATE_DELIVERYBOY_REQUEST = "UPDATE_DELIVERYBOY_REQUEST";
export const UPDATE_DELIVERYBOY_SUCCESS = "UPDATE_DELIVERYBOY_SUCCESS";
export const UPDATE_DELIVERYBOY_RESET = "UPDATE_DELIVERYBOY_RESET";
export const UPDATE_DELIVERYBOY_FAIL = "UPDATE_DELIVERYBOY_FAIL";

export const DELETE_DELIVERYBOY_REQUEST = "DELETE_DELIVERYBOY_REQUEST";
export const DELETE_DELIVERYBOY_SUCCESS = "DELETE_DELIVERYBOY_SUCCESS";
export const DELETE_DELIVERYBOY_RESET = "DELETE_DELIVERYBOY_RESET";
export const DELETE_DELIVERYBOY_FAIL = "DELETE_DELIVERYBOY_FAIL";

export const SINGLE_DELIVERYBOY_REQUEST = "SINGLE_DELIVERYBOY_REQUEST";
export const SINGLE_DELIVERYBOY_SUCCESS = "SINGLE_DELIVERYBOY_SUCCESS";
export const SINGLE_DELIVERYBOY_FAIL = "SINGLE_DELIVERYBOY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";